export const flights = [
    {
      flightName: 'Indigo',
      flightId: '6E 5082',
      fromPlace: 'India',
      fromDate: 'Fri Apr 28 2023 17:14:54 GMT+0530 (India Standard Time)',
      toPlace: 'USA',
      fromAirport: 'Chennai International Airport',
      toAirport: 'John F. Kennedy International Airport',
      image: 'https://static.goindigo.in/content/dam/indigov2/6e-website/downloadapp/Feature-Image.png',
      fromTime: '08:15 AM',
      toTime: '10:05 AM',
      time: '01h50m',
      price: 'Rs. 2,737',
      seats: 60,
    },
    {
      flightName: 'Air India',
      flightId: 'AI 676',
      fromPlace: 'USA',
      fromDate: 'Sat Apr 15 2023 17:14:54 GMT+0530 (India Standard Time)',
      toPlace: 'France',
      fromAirport: 'John F. Kennedy International Airport',
      toAirport: 'Paris Charles de Gaulle Airport',
      image: 'https://logos-world.net/wp-content/uploads/2023/01/Air-India-Logo.png',
      fromTime: '11:25 AM',
      toTime: '01:50 PM',
      time: '02h25m',
      price: 'Rs. 3,450',
      seats: 50,
    },
    {
      flightName: 'SpiceJet',
      flightId: 'SG 2874',
      fromPlace: 'France',
      fromDate: 'Thu Apr 20 2023 17:14:54 GMT+0530 (India Standard Time)',
      toPlace: 'India',
      fromAirport: 'Paris Charles de Gaulle Airport',
      toAirport: 'Chennai International Airport',
      image: 'https://logonoid.com/images/spicejet-logo.png',
      fromTime: '02:35 PM',
      toTime: '05:15 PM',
      time: '02h40m',
      price: 'Rs. 2,899',
      seats: 40,
    },
    {
      flightName: 'Vistara',
      flightId: 'UK 729',
      fromPlace: 'India',
      fromDate: 'Sun Apr 16 2023 17:14:54 GMT+0530 (India Standard Time)',
      toPlace: 'Australia',
      fromAirport: 'Chennai International Airport',
      toAirport: 'Sydney Airport',
      image: 'https://pbs.twimg.com/media/B3B6A-7CUAAjarl?format=jpg&name=small',
      fromTime: '2.30 AM',
      toTime: '08:40 AM',
      time: '01h55m',
      price: 'Rs. 3,125',
      seats: 30,
    },
    {
      flightName: 'Emirates',
      flightId: 'EK 511',
      fromPlace: 'UK',
      fromDate: 'Sun Jun 11 2023 19:40:00 GMT+0530 (India Standard Time)',
      toPlace: 'India',
      fromAirport: 'Heathrow Airport',
      toAirport: 'Bengaluru International Airport',
      image: 'https://logonoid.com/images/emirates-logo.png',
      fromTime: '11:20 PM',
      toTime: '11:55 AM',
      time: '09h25m',
      price: 'Rs. 32,899',
      seats: 20,
    },
    {
      flightName: 'Etihad Airways',
      flightId: 'EY 152',
      fromPlace: 'Australia',
      fromDate: 'Wed Jul 19 2023 15:30:00 GMT+0530 (India Standard Time)',
      toPlace: 'India',
      fromAirport: 'Sydney Airport',
      toAirport: 'Hyderabad International Airport',
      image: 'https://logonoid.com/images/etihad-airways-logo.png',
      fromTime: '09:00 PM',
      toTime: '03:30 AM',
      time: '13h00m',
      price: 'Rs. 18,999',
      seats: 35,
    },


  ];
